#include <iostream>
#include <vector>
#include <algorithm>
#include <assert.h>

#include <unsupported/Eigen/SparseExtra>
#include "AmgclSolver.h"
#include "GeometricMultiGrid.h"


int main(int argc, char *argv[]) {
  Eigen::SparseMatrix<real, Eigen::RowMajor> A;
  ////A.mtx is generated by make_poisson.py
  Eigen::loadMarket(A, "A.mtx");
  Eigen::VectorXd f = Eigen::VectorXd::Constant(A.rows(), 1.0);
  Eigen::VectorXd x = Eigen::VectorXd::Zero(A.rows());

  AmgclSolver::GMGPCG_AMGCL<2>(A,x,f,GeometricMultiGrid::Params()/*=Params()*/);

  return 0;
}